# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=200, unique=True)),
                ('channel', models.CharField(default='System\\Diags', max_length=200)),
                ('value', models.CharField(default='None', max_length=200)),
                ('group', models.CharField(default='System', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=200)),
                ('sex', models.CharField(default='man', max_length=10)),
                ('role', models.CharField(default='father', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='System\\Diags', max_length=200)),
                ('signal', models.TextField()),
            ],
        ),
    ]
