# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='untitled', max_length=200),
        ),
    ]
