# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0002_auto_20170626_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='photo',
            field=models.FileField(default=None, upload_to='humans/', null=True),
        ),
    ]
