# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0004_auto_20170626_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='phone',
            field=models.CharField(default='0124567890', max_length=11),
        ),
    ]
