# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0005_human_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=200)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='None', max_length=200)),
                ('group', models.CharField(default='System', max_length=200)),
            ],
        ),
    ]
