# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0007_rule_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
