# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0008_auto_20170628_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rule',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rule',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
