# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redqueen', '0010_auto_20170628_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='action',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
